- connection: connection1
  ports:
    - id: port1
      synchronization: blocking
      buffersize: 1024
      address:  127.0.0.1:5556
    - id: port2
      synchronization: nonblocking
      buffersize: 1024
      address:  127.0.0.1:5556
  connector:
    - id: connector1
      transport: tcp
      distribution: broker
      interaction: pub-sub
