- id: connection
  transport: tcp
  distribution: broker
  interaction: pub-sub
  port:
    - id: port1 
      synchronization: blocking
      buffersize: 1024
      address:  127.0.0.1:5567
    - id: port2 
      synchronization: blocking
      buffersize: 1024
      address:  127.0.0.1:5567
