# - Try to find ZMQ
# Once done this will define
#
#  ZMQ_FOUND - ZMQ found
#  ZMQ_INCLUDE_DIR - the ZMQ include directory
#  ZMQ_LIBRARY_DIR - ZMQ lib directory
#

SET(ZMQLIB "zmq")

FIND_PATH(ZMQ_INCLUDE_DIR NAMES zmq.h
  PATHS
  $ENV{ROBOTPKG_BASE}/include
	${zmq_PACKAGE_PATH}/install/include
  ENV CPATH
  /usr/include/
  /usr/local/include/
  /opt/local/include/
  NO_DEFAULT_PATH
)

#MARK_AS_ADVANCED("ZMQ_INCLUDE_DIR: "${ZMQ_INCLUDE_DIR})

FIND_LIBRARY(ZMQ_LIBRARY_TMP NAMES ${ZMQLIB} "ZMQLibraries"
  PATHS
  $ENV{ROBOTPKG_BASE}/lib
	${zmq_PACKAGE_PATH}/install/lib
  ENV LD_LIBRARY_PATH
  ENV LIBRARY_PATH
  /usr/lib
  /usr/local/lib
  /opt/local/lib
  NO_DEFAULT_PATH
)

IF(ZMQ_LIBRARY_TMP)
  GET_FILENAME_COMPONENT( ZMQ_LIBRARY_DIR ${ZMQ_LIBRARY_TMP} PATH )
ENDIF(ZMQ_LIBRARY_TMP)

IF(ZMQ_INCLUDE_DIR AND ZMQ_LIBRARY_DIR)
  SET(ZMQ_FOUND TRUE)
ENDIF(ZMQ_INCLUDE_DIR AND ZMQ_LIBRARY_DIR)

# show the ZMQ_INCLUDE_DIR and ZMQ_LIBRARY_DIR variables only in the advanced view
IF(ZMQ_FOUND)
  MARK_AS_ADVANCED(ZMQ_INCLUDE_DIR ZMQ_LIBRARY_DIR )
ENDIF(ZMQ_FOUND)


